const CRITERIA = [
    'ENDPOINT_MATCHES_CLAIM',
    'MAGNITUDE_SUPPORTED',
    'TIMEFRAME_SUPPORTED',
    'SAMPLE_ADEQUATE',
    'METHOD_ROBUST',
    'STATISTICALLY_SIGNIFICANT',
];

const CRITERION_STATUS = ['MET', 'NOT_MET', 'UNCLEAR'];

const VERDICTS = ['JUSTIFIED', 'NOT_JUSTIFIED', 'INSUFFICIENT_EVIDENCE'];

const REVIEW_DECISIONS = ['ACCEPTED', 'OVERRIDDEN'];

const GUARDRAIL_FLAGS = {
    TIMEPOINT_EXCEEDS_STUDY_DURATION: 'TIMEPOINT_EXCEEDS_STUDY_DURATION',
    SMALL_SAMPLE: 'SMALL_SAMPLE',
    BASELINE_ONLY_COMPARATOR: 'BASELINE_ONLY_COMPARATOR',
    NO_STATISTICS_REPORTED: 'NO_STATISTICS_REPORTED',
    EFFECT_OUT_OF_RANGE: 'EFFECT_OUT_OF_RANGE',
};

module.exports = {
    CRITERIA,
    CRITERION_STATUS,
    VERDICTS,
    REVIEW_DECISIONS,
    GUARDRAIL_FLAGS,
};